# theme: jekyll-theme-cayman
title: Mairaj's Portfolio
description: My portfolio of projects

remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

